name: crossle
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2 
  google_mobile_ads: ^4.0.0
  english_words: ^4.0.0
  provider: ^6.0.0
  auto_size_text: ^3.0.0
  mdi: ^5.0.0-nullsafety.0
  soundpool: ^2.2.0
  audio_session: ^0.1.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2" 
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/crosswordMaster.txt
    - assets/frequencyList2.txt
    - assets/soundBell.mp3
    - assets/soundBuzzer.mp3
    - assets/crossleLogo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/crossleIcon.png"  
